CREATE OR ALTER VIEW VWDANFE(
    EMISSCODIGO,
    EMISSTIPO,
    EMISSNOMEFANTASIA,
    EMISSRAZAOSOCIAL,
    EMISSCPFCNPJ,
    EMISSINSCMUNICIPAL,
    EMISSRGIE,
    EMISSCNAE,
    EMISSCRT,
    EMISSENDERECO,
    EMISSORNUMERO,
    EMISSBAIRRO,
    EMISSCIDADE,
    EMISSORCEP,
    EMISSTELEFONE,
    EMISSEMAIL,
    EMISSHOMEPAGE,
    NFISCIDNOTAFISCAL,
    NFISCMODELO,
    NFISCSERIE,
    NFISCSTATUS,
    NFISCNUMERO,
    NFISCTIPO,
    NFISCCHAVEACESSO,
    NFISCOPERACAO,
    NFISCPROTOCOLOAUTORIZACAO,
    NFISCEMISSAO,
    NFISCDATASAIDA,
    NFISCHORASAIDA,
    NFISCTOTALBRUTO,
    NFISCDESCONTO,
    NFISCTOTALLIQUIDO,
    DESTTIPO,
    DESTRAZAOSOCIAL,
    DESTNOMEFANTASIA,
    DESTCPFCNPJ,
    DESTIESTADUAL,
    DESTENDERECO,
    DESTNUMERO,
    DESTBAIRRO,
    DESTMUNICIPIO,
    DESTUF,
    DESTCEP,
    DESTFONE)
AS
Select

Emiss.codigo                     as EmissCodigo,
Emiss.tipo                       as EmissTipo,
Emiss.nomefantasia               as EmissNomeFantasia,
Emiss.razaosocial                as EmissRazaoSocial,
Emiss.cpfcnpj                    as EmissCPFCNPJ,
Emiss.imunicipal                 as EmissInscMunicipal,
Emiss.rgie                       as EmissRGIE,
Emiss.cnae                       as EmissCNAE,
Emiss.crt                        as EmissCRT,
Emiss.endereco                   as EmissEndereco,
Emiss.numero                     as EmissorNumero,
Emiss.bairro                     as EmissBairro,
EmissCid.nome||'/'||EmissCid.uf  as EmissCidade,
Emiss.cep                        as EmissorCEP,
Emiss.telefone                   as EmissTelefone,
coalesce(Emiss.email, '')        as EmissEmail,
coalesce(Emiss.homepage, '')     as EmissHomePage,
NFisc.idnota                     as NFiscIdNotaFiscal,
NFisc.modelo                     as NFiscModelo,
lpad(NFisc.serie, 3 ,'0')        as NFiscSerie,
NFisc.status                     as NFiscStatus,
lpad(NFisc.cnf, 9, '0')          as NFiscNumero,
NFisc.tpnf                       as NFiscTipo,
NFisc.chave                      as NFiscChaveAcesso,
NFisc.natop                      as NFiscOperacao,
NFisc.recebimentoprotocolo       as NFiscProtocoloAutorizacao,
NFisc.dataemissao                as NFiscEmissao,
NFisc.datamovimento              as NFiscDataSaida,
NFisc.hrmovimento                as NFiscHorasaida,
NFisc.tt_vprod                   as NFiscTotalBruto,
NFisc.tt_vdesc                   as NFiscDesconto,
NFisc.tt_vnf                     as NFiscTotalLiquido,
Dest.tipopessoa                  as DestTipo,
Dest.razaosocial                 as DestRazaoSocial,
Dest.nome                        as DestNomeFantasia,
Dest.cgccpf                      as DestCPFCNPJ,
Dest.iestadual                   as DestIEstadual,
Dest.end_endereco                as DestEndereco,
Dest.end_numero                  as DestNumero,
Dest.end_bairro                  as DestBairro,
Dest.end_municipionome           as DestMunicipio,
Dest.end_uf                      as DestUF,
Dest.end_cep                     as DestCEP,
Dest.end_fone                    as DestFone


From

TGerEmpresa Emiss
Left Join TGerCidade EmissCid on (EmissCid.idcidade = Emiss.idcidade)
Left Join TNfeNota NFisc on (NFisc.empresa = Emiss.codigo)
Left Join TNfeDestinatario Dest on (Dest.empresa = NFisc.empresa)and(dest.idnota=NFisc.idnota)
;